// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiXvCXxhnFwSXuO6mwtItXRkgbPTBlpBQ',
    appId: '1:57159075316:web:3711f9aabfd5997202e5a1',
    messagingSenderId: '57159075316',
    projectId: 'talkdok-cf1b4',
    authDomain: 'talkdok-cf1b4.firebaseapp.com',
    storageBucket: 'talkdok-cf1b4.firebasestorage.app',
    measurementId: 'G-QC0P5EL795',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6oyXi05lQLM7xgRIXTm97xyt600h86uM',
    appId: '1:57159075316:android:c61d3944ade8394202e5a1',
    messagingSenderId: '57159075316',
    projectId: 'talkdok-cf1b4',
    storageBucket: 'talkdok-cf1b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkiRPeagxnzBrLR3UShfewhlRyNvqlwwE',
    appId: '1:57159075316:ios:dcb41d5cd3da2f0f02e5a1',
    messagingSenderId: '57159075316',
    projectId: 'talkdok-cf1b4',
    storageBucket: 'talkdok-cf1b4.firebasestorage.app',
    iosBundleId: 'com.example.startup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkiRPeagxnzBrLR3UShfewhlRyNvqlwwE',
    appId: '1:57159075316:ios:dcb41d5cd3da2f0f02e5a1',
    messagingSenderId: '57159075316',
    projectId: 'talkdok-cf1b4',
    storageBucket: 'talkdok-cf1b4.firebasestorage.app',
    iosBundleId: 'com.example.startup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiXvCXxhnFwSXuO6mwtItXRkgbPTBlpBQ',
    appId: '1:57159075316:web:b780a08b8c70c1a302e5a1',
    messagingSenderId: '57159075316',
    projectId: 'talkdok-cf1b4',
    authDomain: 'talkdok-cf1b4.firebaseapp.com',
    storageBucket: 'talkdok-cf1b4.firebasestorage.app',
    measurementId: 'G-0PB7G6NW2N',
  );
}
